Task_2_1_1
tobaffoon/OOP pull request #14
Opened 2023-02-08 17:40 UTC by tobaffoon

2023-02-14 14:41 UTC, tobaffoon commented
Картинку с результатами бенчмарка смотрите в resources

2023-02-14 15:50 UTC, alradish requested changes

2023-02-14 15:50 UTC, alradish commented on Task_2_1_1/src/main/java/ru/nsu/amazyar/MultithreadingPrimeFinder.java
> +        }
Дублирование кода

2023-02-27 11:14 UTC, alradish requested changes

2023-02-27 11:14 UTC, alradish commented on Task_2_1_1/src/main/java/ru/nsu/amazyar/MultithreadingPrimeFinder.java
> +    public boolean containsNoPrimes(List<Integer> list) {
`@Override`

2023-02-28 06:19 UTC, alradish approved these changes

2023-02-28 06:20 UTC, merged