Task_1_2_2
tobaffoon/OOP pull request #6
Opened 2022-10-13 19:21 UTC by tobaffoon

2022-10-13 20:36 UTC, tobaffoon commented
### Не смог выполнить одно условие из примера в тз. 
В нём с помощью stream API нужно было вывести листья с подстрокой "B". 

В моём дереве есть подкласс Node, который задаёт своих сыновей рекурсивно, как иначе представить дерево, у меня идей нет. Я реализую Stream для моего TreeGen<E> через Spliterator<E>, который я реализую через ArrayList<E>, то есть доступ к вершинам непосредственно я иметь не могу. 

Мало того, согласно контракту Iterable<T>, который как мне сказали одногруппники, надо имплементировать, и итератор должен быть generic с типом данных T. 
Это означает, что если всё же я сделаю прямой доступ к вершинам, имплементируя Iterable<TreeGen<E>.Node<E>>, то пользователю придется:

1. Самому доставать из коробки Node значение вершины при работе с Iterator.
2. В качестве аргумента tryAdvance передавать функцию, заворачивающую значение в Node. В частности работа со Stream API становится в 2 раза менее удобной.

Эти два момента, если и не нарушают никаких контрактов, то выглядят очень неприятно. Если выполнение примера первично, то я изменю код, иначе я бы хотел оставить то, что есть

2022-10-14 06:44 UTC, tobaffoon commented
> ### Не смог выполнить одно условие из примера в тз.
> В нём с помощью stream API нужно было вывести листья с подстрокой "B".
> 
> В моём дереве есть подкласс Node, который задаёт своих сыновей рекурсивно, как иначе представить дерево, у меня идей нет. Я реализую Stream для моего TreeGen через Spliterator, который я реализую через ArrayList, то есть доступ к вершинам непосредственно я иметь не могу, а чтобы определить, что вершина - это лист, мне нужно иметь доступ к её полям.
> 
> Мало того, согласно контракту Iterable, который как мне сказали одногруппники, надо имплементировать, и итератор должен быть generic с типом данных T. Это означает, что если всё же я сделаю прямой доступ к вершинам, имплементируя Iterable<TreeGen.Node>, то пользователю придется:
> 
> 1. Самому доставать из коробки Node значение вершины при работе с Iterator.
> 2. В качестве аргумента tryAdvance передавать функцию, заворачивающую значение в Node. В частности работа со Stream API становится в 2 раза менее удобной.
> 
> Эти два момента, если и не нарушают никаких контрактов, то выглядят очень неприятно. Если выполнение примера первично, то я изменю код, иначе я бы хотел оставить то, что есть.
> 
> Способ разобраться со второй проблемой - переопределить методы Stream, если в этом и заключается доп задание (просто обернуть существующий Stream в Node), то я готов это сделать

Поразговаривав с одногруппниками я решил для Tree<E> имплементировать Iterable<E> явно и Iterable<Node<E>> эффективно. С деревом можно будет работать в двух режимах независимо (кроме ConcurrentModificationException): 

1. Как с коллекцией передаваемого типа данных - когда пользователю неважно размещение элементов в структуре
2. Как с коллекцией вершин, в которых лежат данные передаваемого типа - когда пользователю нужна коллекция в виде именно дерева с его особенностями

2022-10-14 06:48 UTC, tobaffoon commented
> ### Не смог выполнить одно условие из примера в тз.
> В нём с помощью stream API нужно было вывести листья с подстрокой "B".
> 
> В моём дереве есть подкласс Node, который задаёт своих сыновей рекурсивно, как иначе представить дерево, у меня идей нет. Я реализую Stream для моего TreeGen<E> через Spliterator<E>, который я реализую через ArrayList<E>, то есть доступ к вершинам непосредственно я иметь не могу, а чтобы определить, что вершина - это лист, мне нужно иметь доступ к её полям.
> 
> Мало того, согласно контракту Iterable<T>, который как мне сказали одногруппники, надо имплементировать, и итератор должен быть generic с типом данных T. Это означает, что если всё же я сделаю прямой доступ к вершинам, имплементируя Iterable<TreeGen.Node<E>>, то пользователю придется:
> 
> 1. Самому доставать из коробки Node значение вершины при работе с Iterator.
> 2. В качестве аргумента tryAdvance передавать функцию, заворачивающую значение в Node. В частности работа со Stream API становится в 2 раза менее удобной.
> 
> Эти два момента, если и не нарушают никаких контрактов, то выглядят очень неприятно. Если выполнение примера первично, то я изменю код, иначе я бы хотел оставить то, что есть.
> 
> Способ разобраться со второй проблемой - переопределить методы Stream, если в этом и заключается доп задание (просто обернуть существующий Stream в Node), то я готов это сделать

Поразговаривав с одногруппниками я решил для Tree\<E\> имплементировать Iterable\<E\> явно и Iterable\<Node\<E\>\> эффективно. С деревом можно будет работать в двух режимах независимо (кроме ConcurrentModificationException): 

1. Как с коллекцией передаваемого типа данных - когда пользователю неважно размещение элементов в структуре
2. Как с коллекцией вершин, в которых лежат данные передаваемого типа - когда пользователю нужна коллекция в виде именно дерева с его особенностями

2022-10-15 18:18 UTC, Leidenn2509 requested changes

2022-10-15 18:18 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/amazyar/TreeGen.java
> +public class TreeGen<E> implements Iterable<E> {
У вас получилась структура дерева, которая на самом деле не дерево, а просто умеет управлять деревом. Я в целом советую избавиться от ненужной обертки. Т.е. перенесите всё что делает Node в TreeGen(ещё наверное стоит переименовать, а то я не совсем понимаю, что означает это название).

2022-10-17 03:15 UTC, Leidenn2509 requested changes
Исправьте замечания по кодстайлу

2022-10-18 10:01 UTC, Leidenn2509 approved these changes

2022-10-23 12:34 UTC, merged