Task_1_2_3
tobaffoon/OOP pull request #8
Opened 2022-10-24 10:39 UTC by tobaffoon

2022-10-27 04:52 UTC, Leidenn2509 requested changes
- Добавить представление графа
- Чтение из файла
- Тесты

2022-10-31 17:46 UTC, tobaffoon commented
Последняя проверка reviewdog не полная, так как там почти лишь неоднозначные требования: пустой catch блок (при чтении графа из файла требуется ловить IOException, но как его обрабатывать в тестах неясно); расстояние между определением переменной и её первым использованием (попытка этого избежать приведёт к потере последовательности логики теста)

2022-11-03 09:13 UTC, alradish approved these changes

2022-11-03 09:13 UTC, alradish commented on Task_1_2_3/src/main/java/ru/nsu/amazyar/Vertex.java
> +    protected boolean wasSorted;
private и сделайте сеттер и геттер

2022-11-03 09:13 UTC, alradish commented on Task_1_2_3/src/main/java/ru/nsu/amazyar/Vertex.java
> +    protected boolean wasSorted;
Но вообще по логике этих полей вообще не должно быть здесь. Эта информация специфична алгоритму и соотвественно надо, чтобы это хранил сам алгоритм

2022-11-28 02:03 UTC, merged